import { Inter } from "next/font/google"

import "./globals.css"
import { Nav } from "@/components/Nav"

const inter = Inter({ subsets: ["latin"] })
import { getCookieTheme } from "@/serverLib"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
  const cookie = await getCookieTheme()

  return (
    <html lang="en">

      <body className={`${inter.className} ${cookie}Theme`} >

        <Nav cookieTheme={cookie}></Nav>
        {children}</body>
    </html >
  )
}
